Repository Ocelot-Social-Community/ocelot.social, pull requests merged in 2024-05, with the labels that each got.

#133 refactor(other): adapt seo and redirect plugin config to theme changes
  docs/.vuepress/config.js
  docs/.vuepress/config/plugins.js
  docs/.vuepress/config/theme.js
  package-lock.json
  package.json
Labels: enhancement, dependencies

#132 chore(other): group dependabot package updates
  .github/dependabot.yml
Labels: enhancement, dependencies

#55 feat(other): development
  .textlintrc.js
  docs/.vuepress/config.js
  docs/.vuepress/config/meta.js
  docs/.vuepress/config/theme.js
  docs/.vuepress/public/society-tile-399x122.png
  docs/.vuepress/styles/palette.scss
  docs/.vuepress/theme/assets/fonts/Noto_Sans/NotoSans-Bold.ttf
  docs/.vuepress/theme/assets/fonts/Noto_Sans/NotoSans-Regular.ttf
  docs/de/README.md
  docs/de/assets/1-to-1-chat.png
  docs/de/assets/group-list.png
  docs/de/assets/group-profile.png
  docs/de/assets/language-selection.png
  docs/de/assets/login.png
  docs/de/assets/map.png
  docs/de/assets/moderation.png
  docs/de/assets/newsfeed.png
  docs/de/assets/notifications.png
  docs/de/assets/single-event.png
  docs/de/assets/single-post.png
  docs/de/assets/system-administration.png
  docs/de/assets/user-profile.png
  docs/de/assets/user-settings.png
  docs/de/contact/README.md
  docs/de/contribute/README.md
  docs/de/donate/README.md
  docs/de/features/README.md
  docs/de/get-started/README.md
  docs/de/imprint/README.md
  docs/de/learn/README.md
  docs/de/privacy-policy/README.md
  docs/en/README.md
  docs/en/contact/README.md
  docs/en/contribute/README.md
  docs/en/donate/README.md
  docs/en/features/README.md
  docs/en/get-started/README.md
  docs/en/imprint/README.md
  docs/en/learn/README.md
  docs/en/privacy-policy/README.md
  docs/fr/README.md
  docs/fr/contact/README.md
  docs/fr/contribute/README.md
  docs/fr/donate/README.md
  docs/fr/features/README.md
  docs/fr/get-started/README.md
  docs/fr/imprint/README.md
  docs/fr/learn/README.md
  docs/fr/privacy-policy/README.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#142 feat(other): add event trigger pull_request to test workflows
  .github/workflows/test-build.yml
  .github/workflows/test-lint.yml
Labels: enhancement
